title: Add It | Digital Marketing & Creative Design Agency
description: >-
  Add It is a digital marketing and creative design agency helping brands grow through content creation, branding, social media marketing, video production, and website design.
email: addit.brand@gmail.com
instagram_username: addit.ltd
author: Add-It
keywords: "add it,add-it,add-it creatives,addit,add it hyderabad,add it agency, digital marketing agency india, creative agency, graphic design agency, branding agency, social media marketing, content creation agency, website design agency, marketing agency for startups"
baseurl: "pages.dev/" # the subpath of your site, e.g. /blog
url: "https://add-it.pages.dev/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
